# Generated by Django 3.0.4 on 2020-03-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_uploadmuisc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadmuisc',
            old_name='name',
            new_name='music_name',
        ),
        migrations.AlterField(
            model_name='uploadmuisc',
            name='file',
            field=models.ImageField(upload_to='static/uploads/musics/'),
        ),
    ]
