# Generated by Django 3.0.4 on 2020-03-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200326_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmuisc',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadmuisc',
            name='path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterModelTable(
            name='uploadmuisc',
            table='upload_music',
        ),
    ]
